---
- hosts: all
  become: yes
  become_user: root
  vars:
    instance_region: "https://usproxy-server.mycompany.aws:8443"

  tasks:
  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: Install following packages
    ignore_errors: true
    yum:
      name: "{{ item }}"
    with_items:
      - tomcat
      - python3
      - python3-pip
      - docker-engine
      - git
      - curl

  - shell: curl http://169.254.169.254/latest/meta-data/placement/availability-zone
    register: instance_region

  - name: Setting environment variable us-west-2a
    command: echo $http_proxy
    environment:
        http_proxy: https://usproxy-server.mycompany.aws:8443
    when: instance_region.stdout in "us-west-2a"

  - name: Setting environment variable us-west-2b
    command: echo $http_proxy
    environment:
        http_proxy: https://usproxy-server.mycompany.aws:8443
    when: instance_region.stdout in "us-west-2b"

  - name: Start service docker and tomcat, if not started
    ignore_errors: true
    service:
      name: docker
      state: restared

    service:
      name: tomcat
      state: restared

  - name: Copy of the local remote file
    copy:
      src: /mycompany-services.tar.gz
      dest: /tmp

  - name: Extract mycompany-services.tar.gz into /data
    unarchive:
      src: /tmp/mycompany-services.tar.gz
      dest: /data
© 2019 GitHub, Inc.
